version: "3.4"

services:

  mysql:
    image: mysql:5.7
    ports:
      - 60001:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${MYSQL_HOST_VOLUME_PATH}:/var/lib/mysql

  php:
    build:
      context: docker/php-ubuntu
      args:
        HOST_USER: ${HOST_USER}
    volumes:
      - ${DOCKER_MOUNT_POINT}:/var/www/html:rw,delegated
      - ./.composer:/var/www/.composer
      # Avoid heavy I/O workloads on bind-mounted volumes
#      - /var/www/html/var/cache
#      - /var/www/html/var/log
      # Custom configuration
      #- ./docker/php/conf.d/custom.ini:/usr/local/etc/php/conf.d/custom.ini:ro
      # SSH keys
      - ~/.ssh:/root/.ssh:ro
    tty: true

  nginx:
    build: docker/nginx
    ports:
      - 443:443
      - 80:80
    volumes:
      - ${DOCKER_MOUNT_POINT}:/var/www/html:rw,delegated
      - ./docker/nginx/conf.d/custom.conf:/etc/nginx/conf.d/symfony.conf:ro
    depends_on:
      - php
    tty: true
    links:
      - php

#  nuxt:
#    build:
#      context: docker/webapp/
#    container_name: nuxt
#    restart: always
#    ports:
#      - "3000:3000"
#    command:
#      "npm run start"
#    volumes:
#      - ./webapp:/app

  frontend:
    build:
      context: ./docker/webapp
      target: 'develop-stage'
    ports:
      - '8080:8080'
    volumes:
      - ./docker/webapp:/app
    command: /bin/sh -c "yarn serve"