version: "3.4"

services:
  database:
    image: postgres:${POSTGRES_VERSION:-13}-alpine
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-db_name}
        # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pass}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
    volumes:
      - ./docker/database/data:/var/lib/postgresql/data:rw

  php:
    build:
      context: .
      target: symfony_php
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD:-pass}@database:5432/${POSTGRES_DB:-db_name}?serverVersion=${POSTGRES_VERSION:-13}
    volumes:
      - php_socket:/var/run/php

  caddy:
    build:
      context: .
      target: symfony_caddy
    depends_on:
      - php
    environment:
      SERVER_NAME: ${SERVER_NAME:-localhost, caddy:80}
    restart: unless-stopped
    volumes:
      - php_socket:/var/run/php
      - caddy_data:/data
      - caddy_config:/config
    ports:
      # HTTP
      - target: 80
        published: 80
        protocol: tcp
      # HTTPS
      - target: 443
        published: 443
        protocol: tcp
      # HTTP/3
      - target: 443
        published: 443
        protocol: udp

volumes:
  php_socket:
  caddy_data:
  caddy_config:

