version: "3.4"

services:
  php:
    build:
      context: .
      target: symfony_php_debug
    volumes:
      - ./:/srv/app
      - ./docker/php/conf.d/symfony.dev.ini:/usr/local/etc/php/conf.d/symfony.ini
    environment:
      XDEBUG_CONFIG: >-
        client_host=host.docker.internal
      XDEBUG_MODE: develop,debug
      PHP_IDE_CONFIG: serverName=symfony
    extra_hosts:
      - "host.docker.internal:host-gateway"

  database:
    ports:
    - 5432:5432