version: "3.4"

services:
  postgre:
    image: postgres:12.2
    restart: always
    environment:
      POSTGRES_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${POSTGRE_HOST_VOLUME_PATH}:/var/lib/postgresql/data
      - ./backups:/data/backups
    ports:
      - 5432:5432

  php:
    build:
      context: docker/php-ubuntu-7.4
      args:
        HOST_USER: ${HOST_USER}
    volumes:
      - ${DOCKER_MOUNT_POINT}:/var/www/html:rw,delegated
      - ./.composer:/var/www/.composer
      - ./docker/php-ubuntu-7.4/7.4/entrypoint.sh:/var/www/entrypoint.sh
    tty: true
    env_file:
      - .env
    entrypoint: /var/www/entrypoint.sh

  nginx:
    build: docker/nginx
    ports:
      - ${DOCKER_NGINX_HTTPS_PORT}:443
    volumes:
      - ${DOCKER_MOUNT_POINT}:/var/www/html:rw,delegated
      - ./docker/nginx/conf.d/symfony.conf:/etc/nginx/conf.d/symfony.conf:ro
    depends_on:
      - php
    tty: true
    links:
      - php
