version: "3.4"

# Development environment override
services:
  php:
    volumes:
      - ./:/srv/app:rw,cached
      - ./docker/php/conf.d/symfony.dev.ini:/usr/local/etc/php/conf.d/symfony.ini
      - ./var:/srv/app/var:rw
    environment:
      APP_ENV: dev

  caddy:
    volumes:
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./public:/srv/app/public:ro


  ###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5432"
    volumes:
      - ./backups:/data/backups
###< doctrine/doctrine-bundle ###