name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup PHP with intl
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: intl-66.1
      - uses: actions/checkout@v2
      - name: Composer Dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: Run Tests
        run: ./vendor/bin/simple-phpunit