name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-18.04

    steps:
      - name: Setup PHP with intl
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: intl-66.1
          tools: composer:v1, cs2pr, phpcs, phpstan
          coverage: xdebug
      - uses: actions/checkout@v2

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Composer Dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Run PHPStan
        run: phpstan analyse src

      - name: Run phpcs
        run: phpcs -q --report=checkstyle src | cs2pr

      - name: Run Tests
        run: ./vendor/bin/simple-phpunit --coverage-clover=coverage.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_IO_TOKEN }}
          file: ./coverage.xml
          flags: unittests
          fail_ci_if_error: true
