name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup PHP with intl
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: intl-66.1
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v1 # or alternative dependency management
      - uses: php-actions/phpunit@v8